apiVersion: apps/v1
kind: Deployment
metadata:
  name: shahnameh
  labels:
    app: shahnameh-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shahnameh-backend
  template:
    metadata:
      labels:
        app: shahnameh-backend
    spec:
      containers:
        - name: shahnameh-backend
          image: ghcr.io/ashkann/shahnameh-backend:0.1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10