apiVersion: v1
kind: Secret
metadata:
  name: google-openid-connect
type: Opaque
stringData:
  clientId: shahnameh
  clientSecret: shahnameh
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: kubernetes.io/basic-auth
stringData:
  username: shahnameh
  password: shahnameh