apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ghcr.io/ashkann/shahnameh/server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          env:
            - name: GOOGLE_OCID_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: shahnameh
                  key: google-ocid-redirect-uri
            - name: GOOGLE_OCID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-openid-connect
                  key: clientId
            - name: GOOGLE_OCID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-openid-connect
                  key: clientSecret
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: shahnameh
                  key: db-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shahnameh
data:
  google-ocid-redirect-uri: "http://shahnameh.xyz/googleOpenIdConnect?"
  db-url: "jdbc:postgresql://postgres:5432/shahnameh"