apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 81
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: assets
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: assets
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi