name: Build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: build docker image
      run: sbt backend/Docker/publishLocal
    - name: push to container registry
      run: docker push ghcr.io/ashkann/shahnameh-backend:0.1.0-SNAPSHOT
