name: Build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: JDK
#      uses: actions/setup-java@v2
#      with:
#        java-version: '8'
#        distribution: 'adopt'
#    - name: Build docker image
#      run: sbt backend/Docker/publishLocal
#    - name: Login to ghrc
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#    - name: Push to ghrc
#    - run: docker push ghcr.io/ashkann/shahnameh-backend:0.1.0-SNAPSHOT

  deploy:
#    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to GKE
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: shahnameh
        location: us-central1-a
        credentials: ${{ secrets.GKE_SA_KEY }}

    # The KUBECONFIG env var is automatically exported and picked up by kubectl.
    - id: get-pods
      run: kubectl get pods
