name: Build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PROJECT_ID: shahname # not shahname*h*
  CLUSTER: shahnameh
  ZONE: us-central1-c
  IMAGE: ghcr.io/ashkann/shahnameh-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'
#      - run: sbt backend/assembly
#      - run: docker build -t ${{ env.IMAGE }} .
#      - uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - run: docker push ${{ env.IMAGE }}

      #  deploy:
      #    needs: build
      #    runs-on: ubuntu-latest
      #    steps:
      - name: Login to GKE
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ env.CLUSTER }}
          location: ${{ env.ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
      # The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - run: ls ${{ github.workspace }}
      - run: kubectl apply -f ${{ github.workspace }}/k8s/deployment.yml