name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'js/**'
      - 'jvm/**'
env:
  SERVER_IMAGE_NAME: ghcr.io/ashkann/shahnameh/server
  ASSETS_IMAGE_NAME: ghcr.io/ashkann/shahnameh/assets

jobs:
  Build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: sbt ShahnamehJVM/assembly
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile.server
          tags: ${{ env.SERVER_IMAGE_NAME }}

      - run: sbt ShahnamehJS/fastLinkJS
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile.assets
          tags: ${{ env.ASSETS_IMAGE_NAME }}

  Deploy-to-DigitalOcean:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - run: doctl kubernetes cluster kubeconfig save shahnameh
    - run: kubectl apply -f ${{ github.workspace }}/k8s