name: Deploy to Digital Ocean
on:
  push:
    branches: [ master ]
    paths:
      - 'k8s/**'
      - '.github/workflows/**'
      - 'js/**'
      - 'jvm/**'
env:
  SERVER_IMAGE_NAME: ghcr.io/ashkann/shahnameh/server
  ASSETS_IMAGE_NAME: ghcr.io/ashkann/shahnameh/assets

jobs:
  Deploy-to-DigitalOcean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - run: sbt ShahnamehJVM/assembly
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile.server
          tags: ${{ env.SERVER_IMAGE_NAME }}

      - run: sbt ShahnamehJS/fastLinkJS
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile.assets
          tags: ${{ env.ASSETS_IMAGE_NAME }}
#      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ${{ env.CONTAINER_REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
##      - uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
##        with:
##          images:
##            - ${{ env.$CONTAINER_REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}
##            - ${{ env.$CONTAINER_REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}